- name: Enable nginx1 via amazon-linux-extras
  command: amazon-linux-extras enable nginx1
  become: true
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

- name: Install nginx
  yum:
    name: nginx
    state: present
  become: true
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: true
